// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbxripakawymprzljekk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ieHJpcGFrYXd5bXByemxqZWtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4OTU2NDcsImV4cCI6MjA2NjQ3MTY0N30.eaoiQmgHU7HE1QgRyiu-mbFKTnGJPVgRSGeuvX2A_00";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});